
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hangman_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: hangman_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
